import { useState, useEffect, useCallback } from 'react';
import { 
  getFirestore, collection, onSnapshot, 
  doc, setDoc, deleteDoc, updateDoc 
} from 'firebase/firestore';
import { QuestionPack } from '@/types/host';
import { toast } from '@/hooks/use-toast';

export function useQuestionPacks() {
  const [packs, setPacks] = useState<QuestionPack[]>([]);
  const [loading, setLoading] = useState(true);

  // 1. Subscribe to Firestore updates (Real-time)
  useEffect(() => {
    const db = getFirestore();
    const unsubscribe = onSnapshot(
      collection(db, 'questionPacks'), 
      (snapshot) => {
        const loadedPacks = snapshot.docs.map(doc => ({
          ...doc.data(),
          id: doc.id // Ensure the ID matches the document ID
        })) as QuestionPack[];
        
        setPacks(loadedPacks);
        setLoading(false);
      },
      (error) => {
        console.error("Error fetching packs:", error);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, []);

  // 2. Add Pack (Save to Firestore)
  const addPack = useCallback(async (pack: QuestionPack) => {
    const db = getFirestore();
    try {
      // We use setDoc with the pack.id to preserve the UUID generated by the app
      await setDoc(doc(db, 'questionPacks', pack.id), pack);
      toast({ title: 'Pack saved to cloud' });
    } catch (err) {
      console.error(err);
      toast({ title: 'Error saving pack', variant: 'destructive' });
    }
  }, []);

  // 3. Update Pack
  const updatePack = useCallback(async (updated: QuestionPack) => {
    const db = getFirestore();
    try {
      const packRef = doc(db, 'questionPacks', updated.id);
      await updateDoc(packRef, { 
        ...updated, 
        updatedAt: new Date().toISOString() 
      });
      toast({ title: 'Pack updated' });
    } catch (err) {
      console.error(err);
      toast({ title: 'Error updating pack', variant: 'destructive' });
    }
  }, []);

  // 4. Delete Pack
  const deletePack = useCallback(async (id: string) => {
    const db = getFirestore();
    try {
      await deleteDoc(doc(db, 'questionPacks', id));
      toast({ title: 'Pack deleted' });
    } catch (err) {
      console.error(err);
      toast({ title: 'Error deleting pack', variant: 'destructive' });
    }
  }, []);

  // 5. Duplicate Pack
  const duplicatePack = useCallback(async (id: string) => {
    const source = packs.find(p => p.id === id);
    if (!source) return;

    const newId = crypto.randomUUID();
    const copy: QuestionPack = {
      ...source,
      id: newId,
      name: `${source.name} (Copy)`,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    
    // Calls the addPack function defined above
    await addPack(copy); 
  }, [packs, addPack]);

  return { packs, loading, addPack, updatePack, deletePack, duplicatePack };
}